spring.application.name=orchid-management

# ===== Server =====
server.port=8005

# ===== SQL Server =====
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=OrchidDBJWT;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ===== JWT =====
application.security.jwt.secret-key=a8d4b6f2c1e9d8c7b6a5f4e3d2c1b0a9f8d7c6e5f4d3b2c1a0f9e8d7c6b5a4f3
application.security.jwt.expiration=600000
